Set time out

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -52,17 +52,23 @@ jobs:
       - run:
           name: Wait for environment update to complete
           command: |
+            counter=0
             while true; do
               status=$(aws elasticbeanstalk describe-environments --application-name sakanu-app --environment-names sakanu-prod --query "Environments[0].Status" --output text)
               if [[ $status == "Ready" ]]; then
                 echo "Environment update completed successfully."
                 break
-              elif [[ $status == "UpdateFailed" ]]; then
-                echo "Environment update failed."
-                exit 1
-              else
+              elif [[ $status == "Updating" ]]; then
                 echo "Environment update is still in progress. Current status: $status"
                 sleep 30
+                counter=$((counter+1))
+                if [[ $counter -ge 20 ]]; then
+                  echo "Environment update timed out after 10 minutes."
+                  exit 1
+                fi
+              else
+                echo "Environment update failed. Final status: $status"
+                exit 1
               fi
             done
 workflows:
